### ISSUE TITLE
Dev Promotion 

### ISSUE THREAD

**Issue by MidgetGems** [dev-protocol/community#11]
Hi Dev team , I've really gotten into the project over the last few months and have been trying my best to promote it to a wider audience as well as making the Telegram and discord channels a friendlier place and trying to answer questions for people there.

Here are some examples of my posts
Reddit
https://www.reddit.com/r/CryptoMoonShots/comments/im2c3n/dev_protocol_new_oracle_now_allows_blockchain/

I post at on average once a day on Channel 4 /Biz: examples below
https://boards.4channel.org/biz/thread/22406834/latest-delphi-digital-report
https://boards.4channel.org/biz/thread/22416022/dev-pumping-after-delphi-digital-report
https://boards.4channel.org/biz/thread/22430000/become-a-dev-samurai-today
https://boards.4channel.org/biz/thread/22366150/your-daily-dose-of-dev

Discord
HypeSquad77Yesterday at 22:57
Do the rewards on stakes.social compound, or accrue separately?
Midget GemsToday at 00:36
Atm separate and you have to claim then (best let it build up a bit first to cover the gas fees)

just crazy08/09/2020
So now i have a wallet zerion but i cant conect it to stakes.social but when i want to make a new one on trust wallet i cant find dev :thinking:
And also which one would i get for staking. There are so much of them and i don't get it anymore.
just crazy08/09/2020
Sorry for all the questions im new to the staking
Midget Gems08/09/2020
No worries crazy we will try to help
I use a pc to connect via metamask, think is does work via trust wallet. You may need to manually add the Dev coin to the wallet by using the contact address
https://community.trustwallet.com/t/how-to-add-a-custom-token/213
Trust Wallet
How to Add a Custom Token
Due to the sheer number of ERC20 tokens out there, in some rare scenarios, the token may not appear on the wallet. Here are the steps that you can do to manually add the token. Step 1. Access Search Token Screen Tap on the toggle sign on the upper right corner of the Wallet ...

https://etherscan.io/token/0x5caf454ba92e6f2c929df14667ee360ed9fd5b26#balances
Ethereum (ETH) Blockchain Explorer
Dev (DEV) Token Tracker | Etherscan
Dev (DEV) Token Tracker on Etherscan shows the price of the Token $3.6180, total supply 12,621,186.981881814159721302, number of holders 1,350 and updated information of the token. The token tracker page also shows the analytics and historical data.

0x5caf454ba92e6f2c929df14667ee360ed9fd5b26
Double check the contract hash for yourself so you know I'm not tricking you (get into that habit for anything crypto)
You should then be able to click the connect button on stakes. Social to stake
Stakers: How & Where to Stake DEV: https://docs.google.com/document/d/1qCvtwMztJ3tecarm--Q48807IMm0uoTqBhTW5u1RofQ/view

Join us at https://stakes.social/
Google Docs
Guide to Staking on the Developer Protocol
Guide to Staking on the Dev Protocol What is staking? Staking is how you support the various creators on the platform, fund their projects. By staking your coins on a creator you are offering them your support and the rewards that come with it. Your coins are not locked up ...

@just crazy let me know if that helps
just crazy08/09/2020
Okey thx mate ill take a look tonight thxx for al the help and support!
Midget Gems08/09/2020
No worries and welcome to Dev :)

# Dev Challange

Dev Protocol related

- [x] Market development 
Promoting Dev

## Address

0xAb0658c66670d93BF47B4b8D5797edD0a60F43A0

# Code of Conduct

By submitting this issue(post), I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/community/blob/main/CODE_OF_CONDUCT.md) 🖖

Hope I have done this correctly, 
MG

**Comment by aggre** [comment]
@MidgetGems Thank you for the entry.

You are entering the category "Market development", but this category applies to software development. Therefore, I believe that your entry properly falls into the "off-site: Write a blog about how to use Dev and Stakes.social and ideas" category. Sorry for the confusion, but please let us know if you have any objections.

**Comment by MidgetGems** [comment]
Hi Aggre

Thanks for the correction, no objections here. My apologies I didn't realize that part was for Software only.
