### ISSUE TITLE
[OTHER] Please add these logo files to brand assets

### ISSUE THREAD

**Issue by yumemayu** [dev-protocol/community#122]
### What would you like to share?

I think we need to publish branding page on devprotocol.xyz website but it needs time to fix design.
So can you add these files brand assets first?

Files:
https://drive.google.com/drive/folders/1S4F9AxIIXk-u6J0nKY46lNrz4pQWbbyK?usp=sharing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
https://github.com/dev-protocol/community/tree/main/branding/assets - done

https://github.com/dev-protocol/community/blob/main/branding/branding.md - for sharing links to other people
