### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by osaguild** [dev-protocol/community#142]
### Name

osaguild

### Discord Username (if applicable)

osaguild

### Additional Context

I learned about devprotocol on Joi ito's podcast. Then I contact with aggre and vincent on twitter and was introduced to their community.
I want to learn and contribute web3 project and project in Japan is better than others because I'm Japanese. I hope dev protocol will be a great service and bring Japanese culture to the world!

**Comment by vinzvinci** [comment]
Thank you for joining us and welcome here 🎉 I invited you to collaborator, where u can access some private channels on Discord. If you have questions there, don't hesitate to ask the team.
