### ISSUE TITLE
dev-challenge-2-exia_ja.md

### ISSUE THREAD

**Issue by narita1980** [dev-protocol/community#2]
[ Please write here something ]
[dev-challenge-2-exia.md](https://github.com/dev-protocol/community/blob/master/bulletins/dev-challenge-2-exia.md)の日本語訳ページとして、[dev-challenge-2-exia_ja.md](https://gist.github.com/narita1980/f210135dcb636e2ed0d51466568e00d9)を作成しました。

# Dev Challange

## What applying for

[ Please replace `[ ]` with `[x]` ]

Dev Protocol related

- [ ] Internationalization suggestions(multi-language)
- [ ] Report typos or sentence mistakes
- [x] Translation implement
- [ ] Fix typos or sentence mistakes
- [ ] Dev Kit(SDK) improvement
- [ ] DApp concept with mocks
- [ ] UI concept with mocks
- [ ] DApp development
- [ ] Market development
- [ ] UI development

off-site

- [ ] Write a blog about how to use Dev and Stakes.social and ideas (Any platform as you like)
- [ ] Create concept art for Dev (illustrations, design, any kind of art with DEV)

## Address

`[0x27ef834D4A530C8ba24006c88e67524A5d30eD27]`

# Code of Conduct

By submitting this issue(post), I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/community/blob/master/CODE_OF_CONDUCT.md) 🖖

**Comment by aggre** [comment]
Thank you for the translation! 翻訳ありがとうございます！

I think this issue falls under **"Translation implement."** What do you think?

---

FYI: "I am Gundam!" は "俺がガンダムだ！" というセリフの引用です😜

**Comment by narita1980** [comment]
@aggre ありがとうございました！

> I think this issue falls under "Translation implement." What do you think?

あまり、その辺りのこだわりないので運営側にその辺りの判断お待たせします。


> FYI: "I am Gundam!" は "俺がガンダムだ！" というセリフの引用です😜

すごい大事な部分だああったので以下修正しました。
https://gist.github.com/narita1980/f210135dcb636e2ed0d51466568e00d9/revisions#diff-e3ea10f3ebb78ecd9940c6b5b34f112d

**Comment by aggre** [comment]
ありがとうございます！

ぜひ PR もお願いします！

"Translation implement" に変更しました。

**Comment by aggre** [comment]
I'll close this issue because the PR is merged ;)
