### ISSUE TITLE
Introduce PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by narita1980** [dev-protocol/community#3]
[ Please write here something ]
Prepare PULL_REQUEST_TEMPLATE.md to make it easy to create a pull request.

# Dev Challange

## What applying for

[ Please replace `[ ]` with `[x]` ]

Dev Protocol related

- [ ] Internationalization suggestions(multi-language)
- [ ] Report typos or sentence mistakes
- [ ] Translation implement
- [x] Other, report or suggestion not related to software
- [ ] Fix typos or sentence mistakes
- [ ] Other, fix source-codes not related to software's core
- [ ] Dev Kit(SDK) improvement
- [ ] DApp concept with mocks
- [ ] UI concept with mocks
- [ ] DApp development
- [ ] Market development
- [ ] UI development

off-site

- [ ] Write a blog about how to use Dev and Stakes.social and ideas (Any platform as you like)
- [ ] Create concept art for Dev (illustrations, design, any kind of art with DEV)

## Address

`[0x27ef834D4A530C8ba24006c88e67524A5d30eD27]`

# Code of Conduct

By submitting this issue(post), I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/community/blob/master/CODE_OF_CONDUCT.md) 🖖

**Comment by aggre** [comment]
Thank you for your suggestion!

I already created that file because you report this issue on Discord.

---

@narita1980  And, I changed your challenge type to "Other, report or suggestion not related to software," so you can reopen this issue if you have a problem.
