### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by ndzhwr** [dev-protocol/community#411]
### Name

Regis NDIZIHIWE

### Discord Username (if applicable)

rnx#3947

### Additional Context

I met Dev Protocol Community here on GitHub, I was searching for open source communities to join and contribute to their projects and have some fun. 
I liked how the community is a large community, so I can meet other open source enthusiasts and learn from each other. I also liked the kind of projects that you have here, I'll be happy to be on of the people under their development.

**Comment by pacifiquem** [comment]
welcome @ndzhwr
