### ISSUE TITLE
typos dev protocol website

### ISSUE THREAD

**Issue by bluow** [dev-protocol/community#5]
[ ERROR NO.1  :   ERROR= A in the sentence "a money designed for OSS"
![no 1](https://user-images.githubusercontent.com/68528878/87901825-a8c9c000-ca75-11ea-87ac-efc97e1a54d7.PNG)
                             FIX= " The money designed for oss"

  ERROR NO.2   :   ERROR="Dev is a new crypto economy" 
![no 2](https://user-images.githubusercontent.com/68528878/87902730-019a5800-ca78-11ea-9e99-9b33622ca92f.PNG) 
                              FIX= "Dev is the new crypto economy"

  ERROR NO.3   :    ERROR= "The more stake, the more rewards you receive."
![NO 3](https://user-images.githubusercontent.com/68528878/87903149-f4ca3400-ca78-11ea-95c1-65532fea0ea9.PNG)

                              FIX= "The more you stake, the more rewards you receive."

  ERROR NO.4   :    ERROR= "more than 1,500 OSS projects have makes 8.4 billion downloads per month" 
![no 4](https://user-images.githubusercontent.com/68528878/87903370-73bf6c80-ca79-11ea-9d21-dd2e3b81e84c.PNG)

                              FIX= "more than 1,500 OSS projects have made 8.4 billion downloads per month"
   
 ERROR NO.5   :    ERROR= "OSS developers have mined 1,583,327 DEV by the Dev Protocol" 
![no 4](https://user-images.githubusercontent.com/68528878/87903530-d0228c00-ca79-11ea-96b8-a6e0ab1675d9.PNG)
                              FIX= "OSS developers have mined 1,583,327 DEV with the Dev Protocol" 
  
 ERROR NO.6   :    ERROR= "It means that the market cap of 71,571 USD distributed to OSS developers " 
![no 4](https://user-images.githubusercontent.com/68528878/87903638-20015300-ca7a-11ea-9262-c763abaa7c79.PNG)
                              FIX="It means that the market cap of 71,571 USD were distributed to OSS developers "
          
  ]

# Dev Challange

## What applying for

[ Please replace one `[ ]` to `[x]` ]

Dev Protocol related

- [ ] Internationalization suggestions(multi-language)
- [x] Report typos or sentence mistakes
- [ ] Translation implement
- [ ] Other, report or suggestion not related to software
- [ ] Fix typos or sentence mistakes
- [ ] Other, fix source-codes not related to software's core
- [ ] Dev Kit(SDK) improvement
- [ ] DApp concept with mocks
- [ ] UI concept with mocks
- [ ] DApp development
- [ ] Market development
- [ ] UI development

off-site

- [ ] Write a blog about how to use Dev and Stakes.social and ideas (Any platform as you like)
- [ ] Create concept art for Dev (illustrations, design, any kind of art with DEV)

## Address

`[ 0xf0f617A2934DB64452FEb443118b26df0f8d36D6 ]`

# Code of Conduct

By submitting this issue(post), I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/community/blob/main/CODE_OF_CONDUCT.md) 🖖

**Comment by aggre** [comment]
@bluow Thank you for the report!

I think those proofreads are legitimate.

Your chosen challenge type [Fix typos or sentence mistakes ] is a fix for the source code, so I don't think it applies in this case. I'm sorry.

If you don't object, I will change the challenge type to [Report typos or sentence mistakes], what do you think?

**Comment by bluow** [comment]
Yes sure change it please, I think I misunderstood it.

**Comment by aggre** [comment]
@bluow Thank you. I fixed the challenge type. Also, I will update the parts that are easily misunderstood.
