### ISSUE TITLE
[FEATURE] Add guidelines for our branding assets

### ISSUE THREAD

**Issue by Panquesito7** [dev-protocol/community#72]
### Detailed description

We need guidelines for our branding assets. That way, users will be able to know what they can and they cannot do with our branding assets/images. @krishguptadev or I can help with that. 🙂

### Context

Having branding guidelines will keep our branding assets securer and ensure no one uses them badly. We'll also let them know in a friendly way what they can do and not do.

### Possible implementation

Add branding guidelines in the `README.md` file.

### Additional information

We should also license our branding assets under the [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) license.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Panquesito7** [comment]
Should I start working on it? I have an idea of the guidelines. 🙂

**Comment by krishguptadev** [comment]
> Should I start working on it? I have an idea of the guidelines. 🙂
> 

Cool! Feel free to!

**Comment by vinzvinci** [comment]
Ping 🏓

**Comment by Panquesito7** [comment]
Going to work on it this week (hopefully). Sorry for the delay. 😅

**Comment by vinzvinci** [comment]
> Going to work on it this week (hopefully). Sorry for the delay. 😅

No worries, just pinging so you won't lose this contribution :D

**Comment by krishguptadev** [comment]
> > Going to work on it this week (hopefully). Sorry for the delay. 😅
> 
> No worries, just pinging so you won't lose this contribution :D

btw i can grab this if you would like 😉
