### ISSUE TITLE
Dev protocol added to OSS.Fund catalog

### ISSUE THREAD

**Issue by bibryam** [dev-protocol/community#8]
[ Created an entry for Dev protocol at [OSS.Fund](https://www.oss.fund/dev-protocol/) and shared it on [twitter](https://twitter.com/bibryam/status/1297084950370541569) 

# Dev Challange

## What applying for

[ Please replace one `[ ]` to `[x]` ]

Dev Protocol related

- [ ] Internationalization suggestions(multi-language) \*Report/suggestions only
- [ ] Report typos or sentence mistakes \*Report/suggestions only
- [ ] Translation implement \*Fix source-codes
- [ ] Other, report or suggestion not related to software \*Report/suggestions only
- [ ] Fix typos or sentence mistakes \*Fix source-codes
- [ ] Other, fix source-codes not related to software's core \*Fix source-codes
- [ ] Dev Kit(SDK) improvement \*Fix source-codes
- [ ] DApp concept with mocks \*Report/suggestions only
- [ ] UI concept with mocks \*Report/suggestions only
- [ ] DApp development \*Develop software
- [ ] Market development \*Develop software
- [ ] UI development \*Develop software

off-site

- [X] Write a blog about how to use Dev and Stakes.social and ideas (Any platform as you like)
- [ ] Create concept art for Dev (illustrations, design, any kind of art with DEV)

## Address

`[0x7d3a900c1987c1a078a72862313bd5fbbd697d4d]`

# Code of Conduct

By submitting this issue(post), I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/community/blob/main/CODE_OF_CONDUCT.md) 🖖

**Comment by bibryam** [comment]
May be [542](https://github.com/dev-protocol/protocol/pull/542) and [524](https://github.com/dev-protocol/protocol/pull/524) can be also considered

**Comment by aggre** [comment]
Thanks a lot!
