### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by Anosh21** [dev-protocol/community#80]
### Name

Anosh Bhakare

### Discord Username (if applicable)

Anosh Bhakare#5653

### Additional Context

Hello there, i would like to get involved in the projects and give my contribution towards it .

**Comment by krishguptadev** [comment]
Welcome to the community!

**Comment by vinzvinci** [comment]
Welcome 🎉

**Comment by Anosh21** [comment]
Thank you 😄
