### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by marpit19** [dev-protocol/community#81]
### Name

Arpit Mohapatra

### Discord Username (if applicable)

Asuna#7535

### Additional Context

I started contributing to  web3community and now want to join as a member and start my contribution to dev-protocol

**Comment by krishguptadev** [comment]
Welcome to the community! Check your email for an invite.

**Comment by marpit19** [comment]
> Welcome to the community! Check your email for an invite.

yeah joined!! 😄
