### ISSUE TITLE
hey i have an idea for a decentralized  fashion recommendation website Please invite me to the community

### ISSUE THREAD

**Issue by fbarulli** [dev-protocol/community#93]
### Name

Fabian

### Additional Context

Im working on an AI project that uses not for profit models, to keep it non-profit, id like to know if theres a way to make it decentralized and pay for its database/server usage

**Comment by vinzvinci** [comment]
Hey @fbarulli, thanks for joining us. You can directly chat in our [discord](https://discord.gg/VwJp4KM) server for your ideas.
