### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by Swastyy** [dev-protocol/community#96]
### Name

Swastika

### Discord Username (if applicable)

Swasty#1957

### Additional Context

I found the community from github by some mutual connections. I am an active open source contributor and interested to join the community. Thanks.

**Comment by vinzvinci** [comment]
Welcome here 🎉

**Comment by Panquesito7** [comment]
Oh, welcome @Swastyy! Glad to have you here! 🥳🎉

**Comment by Swastyy** [comment]
Hey @Panquesito7 Nice to see you. Thanks @vinzvinci 😄

**Comment by yumemayu** [comment]
@Swastyy You have a very cool icon! Welcome here ✨

**Comment by Swastyy** [comment]
> @Swastyy You have a very cool icon! Welcome here ✨

Hey @yumemayu thanks 😃
